with property_seed (
  slug,
  title,
  category_id,
  category_label,
  type,
  operation,
  status,
  location,
  price,
  area,
  bedrooms,
  bathrooms,
  parking,
  description,
  teaser,
  amenities,
  featured,
  published
) as (
  values
    (
      'apartamento-vista-hermosa',
      'Apartamento en Vista Hermosa',
      'apartamento-venta',
      'Apartamentos en Venta',
      'Apartamento',
      'Venta',
      'Disponible',
      'Vista Hermosa, Zona 15',
      '$185,000',
      118,
      3,
      2,
      2,
      'Apartamento con excelente iluminación natural, ambientes integrados y amenidades ideales para familias o inversión.',
      'Vista amplia, ubicación práctica y amenidades de edificio.',
      array['Gimnasio', 'Piscina', 'Seguridad 24/7', 'Salón social']::text[],
      true,
      true
    ),
    (
      'apartamento-zona-catorce',
      'Apartamento en Zona 14',
      'apartamento-renta',
      'Apartamentos en Renta',
      'Apartamento',
      'Renta',
      'Disponible',
      'Zona 14, Guatemala',
      '$1,250/mes',
      96,
      2,
      2,
      2,
      'Apartamento listo para habitar, con acabados modernos y cercanía a comercios, restaurantes y vías principales.',
      'Opción lista para habitar con excelente conectividad.',
      array['Lobby', 'Coworking', 'Terraza', 'Pet friendly']::text[],
      true,
      true
    ),
    (
      'casa-en-renta-carretera',
      'Casa en renta en Carretera',
      'casa-renta',
      'Casas en Renta',
      'Casa',
      'Renta',
      'Disponible',
      'Carretera a El Salvador',
      '$1,800/mes',
      220,
      4,
      3,
      3,
      'Casa amplia en sector residencial, con ambientes cómodos y espacios pensados para vida familiar.',
      'Casa amplia en sector privado, ideal para familia.',
      array['Jardín', 'Pérgola', 'Área de servicio', 'Condominio privado']::text[],
      false,
      true
    ),
    (
      'casa-en-venta-fraijanes',
      'Casa en venta en Fraijanes',
      'casa-venta',
      'Casas en Venta',
      'Casa',
      'Venta',
      'Disponible',
      'Fraijanes',
      '$295,000',
      260,
      4,
      3,
      2,
      'Casa con diseño contemporáneo, espacios sociales amplios y ubicación tranquila dentro de condominio.',
      'Diseño moderno, espacios amplios y entorno tranquilo.',
      array['Condominio', 'Área verde', 'Seguridad', 'Sala familiar']::text[],
      true,
      true
    ),
    (
      'oficina-zona-diez',
      'Oficina en zona corporativa',
      'oficina',
      'Oficinas',
      'Oficina',
      'Renta',
      'Disponible',
      'Zona 10, Guatemala',
      'Consultar',
      80,
      0,
      1,
      2,
      'Espacio de oficina ubicado en sector empresarial, con accesos principales y parqueos disponibles.',
      'Espacio profesional en zona de alto movimiento.',
      array['Recepción', 'Elevadores', 'Parqueo', 'Seguridad']::text[],
      false,
      true
    ),
    (
      'proyecto-residencial-premium',
      'Proyecto residencial premium',
      'proyecto',
      'Proyectos',
      'Proyecto',
      'Venta',
      'Disponible',
      'Sector Oriente',
      'Desde consultar',
      0,
      0,
      0,
      0,
      'Proyecto inmobiliario con diferentes opciones residenciales y amenidades planificadas para estilo de vida moderno.',
      'Nuevo desarrollo con opciones por etapa y disponibilidad.',
      array['Amenidades', 'Etapas disponibles', 'Financiamiento', 'Asesoría']::text[],
      false,
      true
    ),
    (
      'apartamento-inversion-zona-diez',
      'Apartamento para inversión',
      'apartamento-venta',
      'Apartamentos en Venta',
      'Apartamento',
      'Venta',
      'Reservado',
      'Zona 10, Guatemala',
      '$145,000',
      72,
      2,
      2,
      1,
      'Apartamento compacto con buena ubicación y perfil atractivo para inversión o renta posterior.',
      'Opción compacta con alta demanda por ubicación.',
      array['Lobby', 'Parqueo', 'Seguridad', 'Área social']::text[],
      false,
      true
    ),
    (
      'casa-venta-san-cristobal',
      'Casa en San Cristóbal',
      'casa-venta',
      'Casas en Venta',
      'Casa',
      'Venta',
      'Disponible',
      'San Cristóbal',
      '$210,000',
      190,
      3,
      2,
      2,
      'Casa funcional en sector residencial, con distribución cómoda y acceso a servicios principales.',
      'Casa práctica en sector residencial consolidado.',
      array['Patio', 'Sala familiar', 'Parqueos', 'Servicios cercanos']::text[],
      false,
      true
    )
)
insert into public.properties (
  slug,
  title,
  category_id,
  category_label,
  type,
  operation,
  status,
  location,
  price,
  area,
  bedrooms,
  bathrooms,
  parking,
  description,
  teaser,
  amenities,
  featured,
  published
)
select
  slug,
  title,
  category_id,
  category_label,
  type,
  operation,
  status,
  location,
  price,
  area,
  bedrooms,
  bathrooms,
  parking,
  description,
  teaser,
  amenities,
  featured,
  published
from property_seed
on conflict (slug) do update set
  title = excluded.title,
  category_id = excluded.category_id,
  category_label = excluded.category_label,
  type = excluded.type,
  operation = excluded.operation,
  status = excluded.status,
  location = excluded.location,
  price = excluded.price,
  area = excluded.area,
  bedrooms = excluded.bedrooms,
  bathrooms = excluded.bathrooms,
  parking = excluded.parking,
  description = excluded.description,
  teaser = excluded.teaser,
  amenities = excluded.amenities,
  featured = excluded.featured,
  published = excluded.published,
  updated_at = now();

delete from public.property_images
using public.properties
where property_images.property_id = properties.id
  and properties.slug in (
    'apartamento-vista-hermosa',
    'apartamento-zona-catorce',
    'casa-en-renta-carretera',
    'casa-en-venta-fraijanes',
    'oficina-zona-diez',
    'proyecto-residencial-premium',
    'apartamento-inversion-zona-diez',
    'casa-venta-san-cristobal'
  );

with image_seed (slug, url, sort_order) as (
  values
    ('apartamento-vista-hermosa', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', 1),
    ('apartamento-vista-hermosa', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80', 2),
    ('apartamento-vista-hermosa', 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80', 3),
    ('apartamento-zona-catorce', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80', 1),
    ('apartamento-zona-catorce', 'https://images.unsplash.com/photo-1600607688066-890987f18a86?auto=format&fit=crop&w=1200&q=80', 2),
    ('casa-en-renta-carretera', 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80', 1),
    ('casa-en-renta-carretera', 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80', 2),
    ('casa-en-venta-fraijanes', 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=1200&q=80', 1),
    ('casa-en-venta-fraijanes', 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80', 2),
    ('oficina-zona-diez', 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80', 1),
    ('oficina-zona-diez', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80', 2),
    ('proyecto-residencial-premium', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80', 1),
    ('proyecto-residencial-premium', 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&w=1200&q=80', 2),
    ('apartamento-inversion-zona-diez', 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?auto=format&fit=crop&w=1200&q=80', 1),
    ('apartamento-inversion-zona-diez', 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80', 2),
    ('casa-venta-san-cristobal', 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80', 1),
    ('casa-venta-san-cristobal', 'https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=1200&q=80', 2)
)
insert into public.property_images (property_id, url, alt, sort_order)
select properties.id, image_seed.url, properties.title, image_seed.sort_order
from image_seed
join public.properties on properties.slug = image_seed.slug;
