insert into public.categories (id, label, short_label, description, sort_order)
values ('proyecto', 'Proyectos', 'Proyectos', 'Desarrollos inmobiliarios en promocion.', 6)
on conflict (id) do update set
  label = excluded.label,
  short_label = excluded.short_label,
  description = excluded.description,
  sort_order = excluded.sort_order;

with property_seed (
  slug,
  title,
  category_id,
  category_label,
  type,
  operation,
  status,
  location,
  price,
  area,
  bedrooms,
  bathrooms,
  parking,
  description,
  teaser,
  amenities,
  featured,
  published
) as (
  values
    (
      'cetri',
      'Cetri',
      'proyecto',
      'Proyectos',
      'Apartamento',
      'Venta',
      'Disponible',
      'Zona 14',
      'Bajo consulta',
      null::integer,
      null::integer,
      null::integer,
      null::integer,
      'Proyecto inmobiliario disponible bajo consulta directa por WhatsApp.',
      'Proyecto de apartamentos en Zona 14 con informacion completa por WhatsApp.',
      array['Proyecto', 'Apartamentos', 'Zona 14']::text[],
      false,
      true
    ),
    (
      'gamma-ca9',
      'Gamma CA9',
      'proyecto',
      'Proyectos',
      'Bodega',
      'Renta',
      'Disponible',
      'Amatitlan',
      'Bajo consulta',
      null::integer,
      null::integer,
      null::integer,
      null::integer,
      'Proyecto de bodegas disponible bajo consulta directa por WhatsApp.',
      'Bodegas en Amatitlan con informacion completa por WhatsApp.',
      array['Proyecto', 'Bodegas', 'Amatitlan']::text[],
      false,
      true
    ),
    (
      'las-mariposas',
      'Las Mariposas',
      'proyecto',
      'Proyectos',
      'Casa',
      'Venta',
      'Disponible',
      'Antigua Guatemala',
      'Bajo consulta',
      null::integer,
      null::integer,
      null::integer,
      null::integer,
      'Proyecto residencial disponible bajo consulta directa por WhatsApp.',
      'Casas en Antigua Guatemala con informacion completa por WhatsApp.',
      array['Proyecto', 'Casas', 'Antigua Guatemala']::text[],
      true,
      true
    ),
    (
      'los-franciscanos',
      'Los Franciscanos',
      'proyecto',
      'Proyectos',
      'Casa',
      'Venta',
      'Disponible',
      'Antigua Guatemala',
      'Bajo consulta',
      null::integer,
      null::integer,
      null::integer,
      null::integer,
      'Proyecto residencial disponible bajo consulta directa por WhatsApp.',
      'Casas en Antigua Guatemala con informacion completa por WhatsApp.',
      array['Proyecto', 'Casas', 'Antigua Guatemala']::text[],
      false,
      true
    ),
    (
      'minerva',
      'Minerva',
      'proyecto',
      'Proyectos',
      'Apartamento',
      'Venta',
      'Disponible',
      'Zona 2',
      'Bajo consulta',
      null::integer,
      null::integer,
      null::integer,
      null::integer,
      'Proyecto inmobiliario disponible bajo consulta directa por WhatsApp.',
      'Proyecto de apartamentos en Zona 2 con informacion completa por WhatsApp.',
      array['Proyecto', 'Apartamentos', 'Zona 2']::text[],
      false,
      true
    ),
    (
      'nogal-casas',
      'Nogal Casas',
      'proyecto',
      'Proyectos',
      'Casa',
      'Venta',
      'Disponible',
      'Zona 16',
      'Bajo consulta',
      null::integer,
      null::integer,
      null::integer,
      null::integer,
      'Proyecto residencial disponible bajo consulta directa por WhatsApp.',
      'Casas en Zona 16 con informacion completa por WhatsApp.',
      array['Proyecto', 'Casas', 'Zona 16']::text[],
      false,
      true
    )
)
insert into public.properties (
  slug,
  title,
  category_id,
  category_label,
  type,
  operation,
  status,
  location,
  price,
  area,
  bedrooms,
  bathrooms,
  parking,
  description,
  teaser,
  amenities,
  featured,
  published
)
select
  slug,
  title,
  category_id,
  category_label,
  type,
  operation,
  status,
  location,
  price,
  area,
  bedrooms,
  bathrooms,
  parking,
  description,
  teaser,
  amenities,
  featured,
  published
from property_seed
on conflict (slug) do update set
  title = excluded.title,
  category_id = excluded.category_id,
  category_label = excluded.category_label,
  type = excluded.type,
  operation = excluded.operation,
  status = excluded.status,
  location = excluded.location,
  price = excluded.price,
  area = excluded.area,
  bedrooms = excluded.bedrooms,
  bathrooms = excluded.bathrooms,
  parking = excluded.parking,
  description = excluded.description,
  teaser = excluded.teaser,
  amenities = excluded.amenities,
  featured = excluded.featured,
  published = excluded.published,
  updated_at = now();

delete from public.property_images
using public.properties
where public.property_images.property_id = public.properties.id
  and public.properties.slug in (
    'cetri',
    'gamma-ca9',
    'las-mariposas',
    'los-franciscanos',
    'minerva',
    'nogal-casas'
  );

with image_seed (slug, file_name, alt, sort_order) as (
  values
    ('cetri', '01-cover.webp', 'Cetri', 1),
    ('cetri', '02.webp', 'Cetri', 2),
    ('cetri', '03.webp', 'Cetri', 3),
    ('gamma-ca9', '01-cover.webp', 'Gamma CA9', 1),
    ('gamma-ca9', '02.webp', 'Gamma CA9', 2),
    ('gamma-ca9', '03.webp', 'Gamma CA9', 3),
    ('gamma-ca9', '04.webp', 'Gamma CA9', 4),
    ('gamma-ca9', '05.webp', 'Gamma CA9', 5),
    ('las-mariposas', '01-cover.webp', 'Las Mariposas', 1),
    ('las-mariposas', '02.webp', 'Las Mariposas', 2),
    ('las-mariposas', '03.webp', 'Las Mariposas', 3),
    ('las-mariposas', '04.webp', 'Las Mariposas', 4),
    ('las-mariposas', '05.webp', 'Las Mariposas', 5),
    ('las-mariposas', '06.webp', 'Las Mariposas', 6),
    ('los-franciscanos', '01-cover.webp', 'Los Franciscanos', 1),
    ('los-franciscanos', '02.webp', 'Los Franciscanos', 2),
    ('los-franciscanos', '03.webp', 'Los Franciscanos', 3),
    ('los-franciscanos', '04.webp', 'Los Franciscanos', 4),
    ('los-franciscanos', '05.webp', 'Los Franciscanos', 5),
    ('minerva', '01-cover.webp', 'Minerva', 1),
    ('minerva', '02.webp', 'Minerva', 2),
    ('minerva', '03.webp', 'Minerva', 3),
    ('minerva', '04.webp', 'Minerva', 4),
    ('nogal-casas', '01-cover.webp', 'Nogal Casas', 1),
    ('nogal-casas', '02.webp', 'Nogal Casas', 2),
    ('nogal-casas', '03.webp', 'Nogal Casas', 3),
    ('nogal-casas', '04.webp', 'Nogal Casas', 4),
    ('nogal-casas', '05.webp', 'Nogal Casas', 5)
)
insert into public.property_images (property_id, url, alt, sort_order)
select
  public.properties.id,
  'https://hcwxwkoilardbplvwzjc.supabase.co/storage/v1/object/public/property-images/' || image_seed.slug || '/' || image_seed.file_name,
  image_seed.alt,
  image_seed.sort_order
from image_seed
join public.properties on public.properties.slug = image_seed.slug;
